[package]
name = "connect_four"
description = "Connect 4 written in rust"
version = "0.1.7"
authors = ["Will Lane <williamlane923@gmail.com>"]
edition = "2018"
license = "MIT"


[dependencies]
crossterm = "0.18.2"
termion = "1.5.5"
