[package]
name = "connect_four"
description = "Connect 4 written in rust"
version = "0.1.6"
authors = ["Will Lane <williamlane923@gmail.com>"]
edition = "2018"
license = "MIT"


[dependencies]
log-update = "0.1.0"
